apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: purple-wolf-monitor
  labels:
    app.kubernetes.io/name: purple-wolf
    app.kubernetes.io/component: waf-middleware
spec:
  plugin:
    purpleWolf:
      mode: monitor
      groups:
        injection: { enabled: true, mode: enforce }
        signatures: { enabled: true, mode: enforce }
        structural: { enabled: true, mode: monitor }
        reputation: { enabled: true, mode: monitor }
