{{- if and .Values.relay.enabled .Values.relay.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "purple-wolf.fullname" . }}-relay
  labels:
    {{- include "purple-wolf.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.relay.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "purple-wolf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook-relay
{{- end }}
