{{- if and .Values.relay.enabled .Values.relay.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-relay-secrets" (include "purple-wolf.fullname" .)) .Values.relay.secret.name }}
  labels:
    {{- include "purple-wolf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.relay.secret.stringData | nindent 2 }}
{{- end }}
