{{- if and .Values.relay.enabled .Values.relay.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "purple-wolf.fullname" . }}-relay
  labels:
    {{- include "purple-wolf.labels" . | nindent 4 }}
    {{- with .Values.relay.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "purple-wolf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook-relay
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.relay.serviceMonitor.interval }}
{{- end }}
