apiVersion: v2
name: purple-wolf
description: Traefik Web Application Firewall plugin packaging and webhook relay
type: application
version: 0.4.2
appVersion: "0.4.2"
home: https://github.com/guaracloud/purple-wolf
sources:
  - https://github.com/guaracloud/purple-wolf
keywords:
  - traefik
  - waf
  - http-wasm
  - webhook
maintainers:
  - name: GuaraCloud
    url: https://github.com/guaracloud
