apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - networkpolicy.yaml
  - servicemonitor.yaml
patches:
  - path: pdb-min-available.yaml
  - path: relay-resources.yaml
