apiVersion: apps/v1
kind: Deployment
metadata:
  name: purple-wolf-relay
spec:
  template:
    spec:
      containers:
        - name: relay
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
